services:
    bytescreen_doctrine_encrypt.orm_subscriber:
        class: Bytescreen\DoctrineEncryptBundle\Subscribers\DoctrineEncryptSubscriber
        arguments: ["@annotation_reader", "%bytescreen_doctrine_encrypt.encryptor_class_name%", "%bytescreen_doctrine_encrypt.secret_key%"]
        tags:
            -  { name: doctrine.event_subscriber }
    bytescreen_doctrine_encrypt.subscriber:
        alias: bytescreen_doctrine_encrypt.orm_subscriber
    bytescreen_doctrine_encrypt.encryptor:
        class: Bytescreen\DoctrineEncryptBundle\Services\Encryptor
        arguments:
            - "%bytescreen_doctrine_encrypt.encryptor_class_name%"
            - "%bytescreen_doctrine_encrypt.secret_key%"
